import SwiftUI
import WebKit

/// Lessons — an Imprint-style map of every finished lesson & story
/// (public/lessons.html, regenerated by scripts/gen-lessons.js). A 2-wide grid
/// of tiles grouped into sections, plus connected "series" as dashed-arrow
/// paths. Tapping a tile opens that lesson full-screen (a Compare page); a
/// left-edge swipe returns to the map. Ungated and public, so no token is
/// needed. Content ships with a Render deploy — no app build needed to add,
/// reorder, or re-link lessons; this wrapper only hosts the page.
struct LessonsView: View {
    @State private var loadFailed = false
    @State private var reloadKey = 0

    /// The /lessons page's own paper (`body{background:#fdf9f3}`), so the nav
    /// bar matches the page instead of showing a white strip above it.
    static let paper = Color(red: 0.992, green: 0.976, blue: 0.953)

    var body: some View {
        Group {
            if loadFailed {
                VStack(spacing: 14) {
                    Image(systemName: "books.vertical")
                        .font(.system(size: 40))
                        .foregroundStyle(Theme.inkSoft)
                    Text("Couldn't open the Lessons")
                        .font(.headline)
                        .foregroundStyle(Theme.ink)
                    Text("Check the connection and try again.")
                        .font(.subheadline)
                        .foregroundStyle(Theme.inkSoft)
                        .multilineTextAlignment(.center)
                        .padding(.horizontal, 30)
                    Button("Try again") { loadFailed = false; reloadKey += 1 }
                        .font(.subheadline.weight(.semibold))
                        .padding(.horizontal, 18).padding(.vertical, 10)
                        .background(RoundedRectangle(cornerRadius: 6).stroke(Theme.ink, lineWidth: 1))
                        .foregroundStyle(Theme.ink)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Theme.bg)
            } else {
                LessonsWebView(failed: $loadFailed)
                    .id(reloadKey)
                    .ignoresSafeArea(edges: .bottom)
            }
        }
    }
}

/// WKWebView host for /lessons. Back-forward gestures are on so a tapped lesson
/// swipes back to the map; a failed first load flips to the retry state.
private struct LessonsWebView: UIViewRepresentable {
    @Binding var failed: Bool

    func makeUIView(context: Context) -> WKWebView {
        let web = WKWebView(frame: .zero)
        web.navigationDelegate = context.coordinator
        web.isOpaque = false
        web.backgroundColor = UIColor(red: 0.992, green: 0.976, blue: 0.953, alpha: 1) // #fdf9f3 page paper
        web.allowsBackForwardNavigationGestures = true
        if let url = URL(string: MovieService.serverURL + "/lessons") {
            web.load(URLRequest(url: url, cachePolicy: .reloadRevalidatingCacheData, timeoutInterval: 30))
        }
        return web
    }

    func updateUIView(_ web: WKWebView, context: Context) {}

    func makeCoordinator() -> Coordinator { Coordinator(self) }

    final class Coordinator: NSObject, WKNavigationDelegate {
        let parent: LessonsWebView
        init(_ parent: LessonsWebView) { self.parent = parent }

        func webView(_ webView: WKWebView, didFailProvisionalNavigation navigation: WKNavigation!, withError error: Error) {
            // Only the first page load turning up empty counts as a failure; a
            // tapped-through lesson that fails shouldn't blank the whole map.
            if webView.url == nil { parent.failed = true }
        }
    }
}
