import SwiftUI
import UIKit
import WebKit

/// Scratch Pad — stage ONE of a story: thinking with pictures before the
/// Story Room (stage two) makes it a board. Wraps the server's gated
/// /scratchpad page (public/scratchpad.html, regenerated by
/// scripts/gen-scratchpad.py): hearted Playground images arranged as beats
/// with unlabelled color frames. The page owns its whole header (Aug 2026 v2
/// design rule), so this wrapper is a bare WKWebView host that only answers
/// the studio gate's HTTP Basic challenge. Page changes ship with a Render
/// deploy — no app build needed.
struct ScratchPadView: View {
    @AppStorage("forge.studioToken") private var studioToken = ""
    @State private var loadFailed = false
    @State private var reloadKey = 0
    @Environment(\.goBack) private var goBack

    var body: some View {
        Group {
            if loadFailed {
                VStack(spacing: 14) {
                    Image(systemName: "square.dashed")
                        .font(.system(size: 40))
                        .foregroundStyle(Theme.inkSoft)
                    Text("Couldn't open the Scratch Pad")
                        .font(.headline)
                        .foregroundStyle(Theme.ink)
                    Text(studioToken.isEmpty
                         ? "Set the studio token first (Movies ▸ settings gear), then try again."
                         : "Check the connection and try again.")
                        .font(.subheadline)
                        .foregroundStyle(Theme.inkSoft)
                        .multilineTextAlignment(.center)
                        .padding(.horizontal, 30)
                    Button("Try again") { loadFailed = false; reloadKey += 1 }
                        .font(.subheadline.weight(.semibold))
                        .padding(.horizontal, 18).padding(.vertical, 10)
                        .background(RoundedRectangle(cornerRadius: 6).stroke(Theme.ink, lineWidth: 1))
                        .foregroundStyle(Theme.ink)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Theme.bg)
            } else {
                ScratchPadWebView(token: studioToken, failed: $loadFailed, onLeave: goBack)
                    .id(reloadKey)
                    .ignoresSafeArea(edges: .bottom)
            }
        }
    }
}

/// WKWebView host: answers the studio gate's HTTP Basic challenge with the
/// stored token. Same bare pattern as ChatFeedView.
private struct ScratchPadWebView: UIViewRepresentable {
    let token: String
    @Binding var failed: Bool
    /// Leave the tool — what `window.__forgeLeave()` reaches.
    var onLeave: () -> Void = {}

    func makeUIView(context: Context) -> WKWebView {
        let config = WKWebViewConfiguration()
        // The beat popup's mic records her reading a line; playback of notes
        // shouldn't demand a gesture-per-play either.
        config.allowsInlineMediaPlayback = true
        config.mediaTypesRequiringUserActionForPlayback = []
        // THE SAME PAGE IS BEHIND TWO TILES, so it must get the same chrome
        // from both (Aug 2026, Sophie: "make sure the pattern is consistent
        // everywhere"). /storyroom and /scratchpad both serve
        // public/scratchpad.html; the Story Room wrapper hands the header over
        // and this one did not, so the identical page drew a back chevron
        // through one door and none through the other.
        context.coordinator.leaveHandler =
            ForgePageHeader.install(into: config, onLeave: onLeave)
        let web = WKWebView(frame: .zero, configuration: config)
        web.navigationDelegate = context.coordinator
        web.uiDelegate = context.coordinator
        web.isOpaque = false
        web.backgroundColor = UIColor(red: 0.965, green: 0.949, blue: 0.914, alpha: 1) // page --paper #f6f2e9
        web.allowsBackForwardNavigationGestures = false
        if let url = URL(string: MovieService.serverURL + "/scratchpad") {
            web.load(URLRequest(url: url, cachePolicy: .reloadRevalidatingCacheData, timeoutInterval: 30))
        }
        return web
    }

    func updateUIView(_ web: WKWebView, context: Context) {}

    func makeCoordinator() -> Coordinator { Coordinator(self) }

    final class Coordinator: NSObject, WKNavigationDelegate, WKUIDelegate {
        // iOS reclaims the web content process under memory pressure (this
        // app keeps three tools alive at once). A bare reload() here made it
        // WORSE — all three resurrecting together re-spiked memory and iOS
        // killed them in a loop, blanking the tool she was reading every ~10s
        // (build 175). ForgeWebRevive reloads only the visible view, one at a
        // time; a hidden tool revives when she switches back to it.
        func webViewWebContentProcessDidTerminate(_ webView: WKWebView) {
            ForgeWebRevive.shared.terminated(webView)
        }
        let parent: ScratchPadWebView
        /// `addScriptMessageHandler` does NOT retain — hold the leave bridge
        /// here or `window.__forgeLeave()` reaches nothing.
        var leaveHandler: ForgeLeaveHandler?
        init(_ parent: ScratchPadWebView) { self.parent = parent }

        // The mic icon records via getUserMedia — grant the capture request
        // (the OS mic permission prompt still applies the first time).
        @available(iOS 15.0, *)
        func webView(_ webView: WKWebView, requestMediaCapturePermissionFor origin: WKSecurityOrigin,
                     initiatedByFrame frame: WKFrameInfo, type: WKMediaCaptureType,
                     decisionHandler: @escaping (WKPermissionDecision) -> Void) {
            decisionHandler(type == .microphone ? .grant : .deny)
        }

        // The /scratchpad page sits behind HTTP Basic (any user, password = token).
        func webView(_ webView: WKWebView,
                     didReceive challenge: URLAuthenticationChallenge,
                     completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
            if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodHTTPBasic,
               challenge.previousFailureCount == 0 {
                completionHandler(.useCredential,
                                  URLCredential(user: "sophie", password: parent.token, persistence: .forSession))
            } else if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
                completionHandler(.performDefaultHandling, nil)
            } else {
                completionHandler(.cancelAuthenticationChallenge, nil)
            }
        }

        func webView(_ webView: WKWebView, didFail navigation: WKNavigation!, withError error: Error) {
            parent.failed = true
        }
        func webView(_ webView: WKWebView, didFailProvisionalNavigation navigation: WKNavigation!, withError error: Error) {
            parent.failed = true
        }
        func webView(_ webView: WKWebView, decidePolicyFor navigationResponse: WKNavigationResponse,
                     decisionHandler: @escaping (WKNavigationResponsePolicy) -> Void) {
            if let http = navigationResponse.response as? HTTPURLResponse, http.statusCode == 401 {
                parent.failed = true
                decisionHandler(.cancel)
                return
            }
            decisionHandler(.allow)
        }
    }
}
