# The chapter spine of this chat. Each entry: (first message index, title, l1, l2)
# KIND is looked up below — lessons pink, experiments yellow, research blue,
# everything else (building the tools) mint. Sophie's colours, Aug 2026.
# Ranges run to the next chapter's start; l3 is the real messages, sliced live.
CHAPTERS = [
 (0, "The Story Room, renamed",
  "You asked me to look at your Story Room and said “beats” was the wrong word — it should read like a summary. I went and did it instead of talking it through with you first, which you flagged.",
  ["The rename: beats → a **summary** of key moments, and **chunks** for the pieces that belong together.",
   "You wanted the conversation BEFORE the build. I built first. Noted at the time and it kept mattering all week.",
   "This is the seed of everything after — the shape of a story is what the lessons ended up being about."]),

 (9, "How the brain encodes stories",
  "A real research detour: how memory actually chunks a story, and what sleep does to it. You said my explanation lost you — and that losing you was the useful signal.",
  ["Chunking, re-encoding during sleep, why a story survives retelling but the details drift.",
   "Your read: if the standard explanation loses a smart person, the explanation is the problem — not the person.",
   "Out of this came the whole project: **teach the elusive thing as a TikTok** — someone thinks they're watching something fun and learns the concept sideways.",
   "The method you set: keep the ABSTRACT CONCEPT as the spine; hang small metaphors off each part; never let one metaphor carry the whole thing."]),

 (22, "Astrology — the first lesson",
  "The first real lesson. Not “astrology is true” and not “astrology is stupid” — the argument that as-above-so-below is fine and the CURRENT practice is what's broken.",
  ["Two wheels (signs and houses) mapped onto the two rotations everybody already knows — earth spinning, earth going round the sun.",
   "Your hook: everyone knows there aren't twelve personalities — so the failure is in the mapping, not the premise.",
   "Images you specified: the mirrored pool for as-above-so-below; two girls at dinner with twelve coloured circles over their heads, one of them GARRULOUS.",
   "Your rule landed here: **no contact sheets** — every image goes into the Assets tab individually and labeled."]),

 (69, "ADHD & Autism",
  "Your take: we took something genuinely complicated, tried to simplify it, and kept making it more complicated. It's the genes.",
  ["Built from your October journal pages — you sent the scans and then your own transcription of them.",
   "Spectrum vs cluster vs “it's just the genes”; the double helix; the TikTok-everything-is-ADHD ending.",
   "You deliberately held your notes back to see my version first, then gave yours so we could take the best of both.",
   "I corrected you on “it's not just genes” — you'd said it IS just genes, which is what you meant. That correction reflex became a thing to watch."]),

 (99, "General Dysphoria",
  "Dysphoria isn't only about gender. Your example: you're 4'11\" and 34 and people read you as 22, and you don't get respected for it.",
  ["The lesson extrapolates from one specific mismatch to the general case — everyone has one.",
   "You asked for a different lead example (you're sensitive about that one) and three examples instead of one.",
   "Your January journal diagrams fed this: the girl with a snake coming out of her, the alien unzipping her own human face."]),

 (106, "Everything at once — the whole set of lessons",
  "You said “let's just go for it” — make all the images for every lesson we'd thought of and turn them into decks.",
  ["The batch run that produced most of the card art.",
   "You offered your Substack essays as more source material.",
   "You caught a technical bug: only the first lesson was showing.",
   "You sent the whole ZIP of your writing rather than picking pieces out of it."]),

 (125, "OCD & Witchcraft",
  "You said it honestly: this one is different — a personal essay with a narrative arc, not an explainer like the others.",
  ["So it got its own treatment rather than being forced into the explainer shape.",
   "Split into parts (part one / part two).",
   "The witch-lesson pipeline detail you pointed me at: sample the background hex out of each finished image and set the slide to that exact colour, so the art dissolves into the page."]),

 (149, "Inside & Outside Thoughts",
  "Cognitive vehicles: thoughts that aren't true but get you from one place to the next — and knowing which ones are for you and which are for other people.",
  ["Your uncle Corey explaining his whole family in therapy language; useful for him, inside thoughts, private, keep out.",
   "The mirror affirmation: you can say “I'm beautiful, I'm strong” to yourself; you can't hand that to other people and require them to hold it.",
   "The 5'8\" date: he can like his own height and still not like how it lands in the world — accepting the disconnect buys you room.",
   "Your ex saying “that's negative self-talk, go to therapy” about “I'm an ungrateful bitch” — but that's not how you talk to yourself when it's just you.",
   "Aunt Parvati's sudden spiritual name first appears here — she came back as a drawing on the last day."]),

 (157, "The Metaphor Machine",
  "How you think about art: a machine in your head that takes in raw material — things people say, books, moments — and strips them into abstraction.",
  ["The evolving metaphor critique: not good/bad, but “it's like this… no, like this” — either closing in on the thing, or each metaphor sharing one trait with it.",
   "Pattern collecting as a near-religious act: matchboxes tied all over your body, and anything matching a pattern goes in its box.",
   "Kit vs set — a tea set (different pieces, one look) against a first aid kit (nothing in common but purpose).",
   "The set-theory lesson (from the card game SET) was parked here as the sibling idea."]),

 (168, "Read People",
  "Your own booklet — you sent the PDF — rebuilt as a lesson in the house style.",
  ["The instruction: same amount of text and image per page as the others, use my judgement on how many.",
   "Later redone from scratch because the first pass invented diagrams instead of recreating YOURS.",
   "That redo is what set the standing rule: rebuild faithfully from the source, and if unsure, read the transcript again."]),

 (182, "Valued Customer — the coffee story",
  "You sent a voice memo of the night you drank too much coffee, took the train downtown, and the whole thing unravelled. It became a film in your own voice.",
  ["Your recording is the spine — deadpan telling, cut tight; laughs, farts and long pauses trimmed out.",
   "The tight cut: **2 minutes 6 seconds**, 14 beats, ending on the penny.",
   "Six beats animated (coffee jitter, highway dash, track dodge, siren leap, dogs, penny); the rest stills with a slow push.",
   "You asked for TikTok length. A second story was recorded and deliberately held — it's still unbuilt."]),

 (211, "The 1 → 2 → 3 queue",
  "You asked what was on the queue and then said “go 1 → 2 → 3”: Read People redone faithfully, your diary diagrams converted to house style, and the Meditation lesson.",
  ["**What Do You Want to Wake Up To?** came out of this — Mason in the sauna saying “just meditate” against you drowning in a ball pit.",
   "Traditional CBT (push each thought back one at a time) vs the version where one big idea pops the whole crowd.",
   "It lands on your contrast: the dumpster versus the pine forest — what do you want to be inside when you go down into your thoughts."]),

 (232, "The palette experiment — warm → pastel",
  "The biggest experiment in the chat: you asked whether the colour palette could change, and we ran the whole look through variants.",
  ["Warm (golden yellow, salmon, orange on cream) → pastel (lilac, pink, mint, pale yellow).",
   "You wanted the background WHITE, not lilac — done in post as a flood-fill from the border, since the model always tints it.",
   "You asked exactly how the hex codes got in and how the prompt changed — the beginning of your prompt-accuracy thread.",
   "**Pastel variant 2** is the one you settled on, and it later became a real Test Station style.",
   "This chapter is why the prompts drifted: the style text changed several times across the run, and I didn't say so at the time."]),

 (272, "Where Do You Crop Art?",
  "Mason's noise art — a pipeline you dictated in full: sound bites sucked through a fuchsia pipe, a squeegee accordion pipe, a teal mop, landing framed on a gallery wall.",
  ["The real question: who is the artist — the one who made the noise, or the one who found meaning in it?",
   "Corner cards, deliberately not lesson cards: the beef jerky being pulled apart, the white rectangle splitting into two.",
   "Zoom-out diagrams as a recurring device: “that was an example of a bigger thing, and you are here inside it.”",
   "It ends on your checkout-counter sculpture — nobody can tell if you arranged the groceries or just want to eat them.",
   "Rebuilt faithfully later, after the first version lost your corner pieces."]),

 (301, "Notes, votes and prompts on the assets",
  "The review loop got real: 40 asset notes waiting, and the rule that every image must carry the exact prompt it was made from, split style / content.",
  ["You asked for a way to see which noted images were already handled — it shouldn't be manual.",
   "You parked a morning's worth of ideas here so they wouldn't be lost (rituals, self-care studio, sticker packs, the SET cards).",
   "The prompt-posting rule arrived mid-chat and everything after had to comply.",
   "You also raised the meta-task: what we're really doing is synthesising information so people can actually hold it."]),

 (327, "Imprint, the shapes, and Crop Art rebuilt",
  "A detour into how to LOOK at all this — the Imprint screenshots, the Compare tab getting crowded, a story summarised as a shape — and then Crop Art rebuilt faithfully.",
  ["Nodes and relationships, with the relationship itself drawn rather than implied.",
   "You asked for a specific shape for Evan and another for Charlie — conceptualised, not drawn.",
   "The APIFRAME/Midjourney credits question came up here and the key never turned up.",
   "**Crop Art was rebuilt from your own words**, corner metaphors and diagrams included — the version that stuck.",
   "Your instruction for it: don't rewrite the lesson, use it as the first test of the metaphors-and-diagrams idea."]),

 (428, "The prompt has to be the prompt",
  "Two things you pinned down in one stretch: where the Assets-tab images had gone, and that a filed prompt has to be the literal text that was sent.",
  ["The missing images were a hard cap in the tab, not a deletion — the oldest were never being sent. You had another chat fix it.",
   "You also spotted double-posting: once automatically by the hook, once by me with the prompt.",
   "**A re-roll is the ORIGINAL prompt plus only the flagged change** — the sauna image is what settled it, and it is a repo rule now.",
   "**And a prompt is filed verbatim, never paraphrased.** “The whole point of me asking for the prompt was to have the prompt.”",
   "The beef jerky belonged as a corner card, not a lesson card — your correction."]),

 (481, "The Lessons hub",
  "You asked for the artifact with all the lessons to live in the app properly. First question you asked: web page or TestFlight build every time?",
  ["Web page — so future changes ship with a deploy and never need a build.",
   "Shipped as `/lessons`, generated by a script, with a tile on the iOS home.",
   "Another chat later added the VOICES row to it."]),

 (489, "“Only answer if you know the truth”",
  "You asked how many styles were actually used, said you thought it was two, and told me to look at the records rather than answer from memory.",
  ["The honest answer was **twelve** style variants across the run, not two.",
   "You asked for a compare artifact showing every exact prompt beside the images it made.",
   "You sent it back twice: no way out of the lightbox, the page scrolling behind it, and no way to collapse sections.",
   "Then you caught that the style prompts shown were incomplete — the ending line was missing. Rebuilding that sheet properly is still on the list."]),

 (514, "Pastel variant 2 into the Test Station",
  "You picked pastel variant 2 as the look and asked for it as a Test Station style — exact same prompt, same reference images, same quality.",
  ["I had the quality wrong (low, not medium) and you caught it by asking rather than assuming.",
   "Then: “I don't see the tile.” Three times. Because I'd been editing the WEB Test Station the whole time and you only ever look at the iOS app.",
   "That's what surfaced the split: the app's Test Station was native Swift with the styles hardcoded.",
   "Your call: turn it into a web page."]),

 (552, "Which model was I talking to?",
  "You realised you thought you'd been talking to Fable and were actually talking to Opus, and asked me to find the exact switch point in the conversation.",
  ["Verified from the transcript, not from memory: **Fable wrote the first 57 assistant records** — July 28, the story-room and astrology stretch — and Opus wrote every one after. One clean split, no interleaving.",
   "You made me double-check the whole thing rather than just the one message you cared about.",
   "You asked about branching a chat, copy-paste blocks vs markdown files, and whether a clean chat beats continuing here.",
   "The Fable stretch was pulled out verbatim as markdown for you — deliberately not committed anywhere, since it's personal."]),

 (571, "The Test Station as a web page",
  "Following through on the split: the native Test Station became a served page so it changes without a build.",
  ["Another chat later replaced it again with a native version that reads its styles from the server — which is the better answer, so I took theirs during the merge.",
   "Still open from this stretch: Warm and Dreams tiles, and the cream-vs-white ending question you never answered."]),

 (579, "The exact prompts, verbatim",
  "You asked for a document with every prompt I'd used, split style and content, verbatim — no paraphrasing.",
  ["Also your question about why the style-reference animals never leaked into my images when other chats were fighting that.",
   "The document became `docs/imprint-lessons/exact-prompts.md` — 352 prompts, committed to the repo."]),

 (583, "Backfilling your messages",
  "You pasted precise instructions to lift your own side of this conversation into the Chats app, with a hard rule: if there's no transcript, say so and post nothing.",
  ["Posted from the real transcript, filtered of machinery, with your true send times.",
   "Found a live bug doing it: the reply route ignores the id field, so there's no dedupe — my run created 151 duplicates, which I then cleaned out.",
   "That means your canned instruction will double-post in any chat that's already been backfilled."]),

 (586, "Everything has a home",
  "You wanted to be sure nothing we made lived only inside this chat.",
  ["Rescued and uploaded: the Valued Customer videos and clips, the voiceover, and 31 stray PNGs.",
   "Committed to the repo: 56 spec files, 27 builder scripts, and the verbatim prompt document (PR #972).",
   "The audit found 679 assets already safe in Storage — the gaps were narrow and are now closed."]),

 (593, "The 21 lessons on the shelf",
  "You asked for all the lessons to live in the Story Room — “put them all on the shelf” — and said to make sure the narrations stayed with them.",
  ["Every lesson became a real story: its cards in order as beats, each carrying that card's narration text.",
   "Your nine read-aloud recordings travel on the stories that have them.",
   "Animal Magic's two films were located and attached to it.",
   "First I answered your question about which lessons were already there — two — before adding anything."]),

 (600, "Inboxes, the cover, and Aunt Parvati",
  "Three asks at once: give each story its own inbox instead of pointing at Playground hearts, let you choose the main image, and draw your aunt Parvati.",
  ["17 stories filled with their own iteration images — every version of every card, filed to its lesson.",
   "The cover picker: a button in a beat's popup pins that image as the story's cover on the shelf.",
   "The Meditation story's cover moved from Mason to you waking up in bed stretching.",
   "Parvati drawn at medium — salt-and-pepper curls, glasses, cross-legged, deliberately not the recurring young woman."]),

 (605, "In your own words",
  "You asked me to pull out everything you'd said about each story and make it a description field — and where it was audio, leave it as audio.",
  ["**19 stories** carry a description now: 12 with your words as text, cut from this transcript by exact match and never paraphrased.",
   "**10 carry audio** — your read-alouds, plus the coffee story as you told it. Three carry both.",
   "The coffee-story recording and the unbuilt second story were still only on this container's disk — both banked to Storage and filed into the memo library.",
   "Then you asked how to actually OPEN them, which was fair: nothing displayed it. The About-this-story sheet is that."]),
]


KIND = {'The Story Room, renamed': 'build', 'How the brain encodes stories': 'research', 'Astrology — the first lesson': 'lesson', 'ADHD & Autism': 'lesson', 'General Dysphoria': 'lesson', 'Everything at once — the whole set of lessons': 'lesson', 'OCD & Witchcraft': 'lesson', 'Inside & Outside Thoughts': 'lesson', 'The Metaphor Machine': 'lesson', 'Read People': 'lesson', 'Valued Customer — the coffee story': 'lesson', 'The 1 → 2 → 3 queue': 'lesson', 'The palette experiment — warm → pastel': 'experiment', 'Where Do You Crop Art?': 'lesson', 'Notes, votes and prompts on the assets': 'build', 'Imprint, the shapes, and Crop Art rebuilt': 'build', 'The prompt has to be the prompt': 'build', 'The Lessons hub': 'build', '“Only answer if you know the truth”': 'experiment', 'Pastel variant 2 into the Test Station': 'experiment', 'Which model was I talking to?': 'research', 'The Test Station as a web page': 'build', 'The exact prompts, verbatim': 'build', 'Backfilling your messages': 'build', 'Everything has a home': 'build', 'The 21 lessons on the shelf': 'build', 'Inboxes, the cover, and Aunt Parvati': 'build', 'In your own words': 'build'}
