#!/usr/bin/env python3
"""
nde-grab-local.py — run this on YOUR OWN Mac. Give it Anthony Chene YouTube
links; it downloads each video's audio + captions from your home connection and
banks them in Firebase in EXACTLY the layout the NDE cutting pipeline reads.

Why local: cloud/datacenter IPs are bot-blocked by YouTube ("Sign in to confirm
you're not a bot"), so the downloads have to come from a residential connection.
Everything after that (theme mining, the Episode Editor, supercuts) already runs
in the cloud off what this script banks.

WHAT IT WRITES (matches the 69 videos already banked — verified against live data)
  Storage : nde-audio/<videoId>.<ext>   (public; raw bestaudio, .webm/opus by
            default — no re-encode, same as every file already up there)
  URL     : https://storage.googleapis.com/<bucket>/nde-audio/<videoId>.<ext>
  Firestore: forge-nde-videos/<videoId>
            { videoId, url, title, publishedAt, channelTitle, channelId,
              duration, description, transcript:{ source, language,
              autoGenerated, segments:[{start,dur,text}], full, fetchedAt },
              audioUrl, audioBytes, status, createdAt, updatedAt }
            Written with merge — any moments/summary/experiencerName already
            extracted are preserved, never clobbered.

SETUP (one time)
  brew install yt-dlp ffmpeg
  pip3 install google-cloud-storage google-cloud-firestore
  # Credentials: AirDrop the Deck Factory (deckfactory-43176) service-account
  # JSON to this Mac — it lands in ~/Downloads and the script FINDS IT THERE
  # AUTOMATICALLY (also checks ~/Desktop, ~/Documents, ~/keys). Power users can
  # still set GOOGLE_APPLICATION_CREDENTIALS / FIREBASE_SERVICE_ACCOUNT instead.

RUN (easiest — paste mode)
  python3 scripts/nde-grab-local.py
  # ...then paste ALL your links at once (any format, commas or lines) and
  # press Return on an empty line.

RUN (other ways)
  python3 scripts/nde-grab-local.py "https://www.youtube.com/watch?v=XXXXXXXXXXX" \
                                    "https://www.youtube.com/watch?v=YYYYYYYYYYY"
  python3 scripts/nde-grab-local.py --file urls.txt
  python3 scripts/nde-grab-local.py --dry-run <url>       # show the plan, no network
  python3 scripts/nde-grab-local.py --force <url>         # re-download + re-upload

Accepts full watch URLs, youtu.be/…, /shorts/…, /embed/…, or bare 11-char ids.
Playlist URLs are rejected unless you pass --yes-playlist (then every video in
it is grabbed). Safe to re-run: anything already banked is skipped.

OPTIONS
  --file PATH          read one url/id per line (# comments ok)
  --force              re-download and re-upload even if already banked
  --dry-run            print the plan; no YouTube, no Firebase, no uploads
  --yes-playlist       expand playlist URLs instead of rejecting them
  --audio-format FMT   source (default, no re-encode) | mp3 | m4a
  --keep DIR           keep the downloaded files in DIR instead of a temp dir
  --bucket NAME        override the Storage bucket
  --collection NAME    override the Firestore collection (forge-nde-videos)

Nothing here costs money: yt-dlp + Firebase writes only, no paid API calls.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone

COLLECTION = os.environ.get("NDE_COLLECTION", "forge-nde-videos")
AUDIO_PREFIX = os.environ.get("NDE_AUDIO_PREFIX", "nde-audio/")
# yt-dlp's own retry/sleep settings — polite, and survives YouTube throttling.
YTDLP_COMMON = ["--no-warnings", "--retries", "5", "--extractor-retries", "3"]

CONTENT_TYPES = {
    "webm": "audio/webm",
    "m4a": "audio/mp4",
    "mp4": "audio/mp4",
    "opus": "audio/opus",
    "ogg": "audio/ogg",
    "mp3": "audio/mpeg",
    "wav": "audio/wav",
}


def log(msg):
    print(msg, flush=True)


def now_iso():
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")


# ── input parsing ──────────────────────────────────────────────────────

ID_RE = re.compile(r"^[A-Za-z0-9_-]{11}$")
URL_ID_RE = re.compile(r"(?:v=|/shorts/|/embed/|youtu\.be/|/live/)([A-Za-z0-9_-]{11})")


def parse_video_id(text):
    """Mirror of nde.js parseVideoId — any YouTube URL shape or a bare 11-char id."""
    s = (text or "").strip()
    if ID_RE.match(s):
        return s
    m = URL_ID_RE.search(s)
    return m.group(1) if m else None


def is_playlist_url(text):
    s = (text or "").strip()
    if "list=" not in s:
        return False
    # watch?v=<id>&list=<pl> is a video *in* a playlist — treat it as the video.
    return parse_video_id(s) is None


# ── yt-dlp ─────────────────────────────────────────────────────────────

def ytdlp_bin():
    for cand in ("yt-dlp", "/opt/homebrew/bin/yt-dlp", "/usr/local/bin/yt-dlp"):
        path = shutil.which(cand) if "/" not in cand else (cand if os.path.exists(cand) else None)
        if path:
            return path
    return None


def run_ytdlp(binary, args, capture=True):
    proc = subprocess.run(
        [binary] + YTDLP_COMMON + args,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE,
        text=True,
    )
    if proc.returncode != 0:
        tail = (proc.stderr or "").strip().splitlines()
        raise RuntimeError((tail[-1] if tail else "yt-dlp failed").replace("ERROR: ", "")[:220])
    return proc.stdout or ""


def expand_playlist(binary, url):
    out = run_ytdlp(binary, ["--flat-playlist", "--print", "%(id)s", url])
    ids = [line.strip() for line in out.splitlines() if ID_RE.match(line.strip())]
    if not ids:
        raise RuntimeError("playlist expanded to zero videos")
    return ids


def fetch_meta(binary, video_id):
    raw = run_ytdlp(
        binary,
        ["--dump-single-json", "--skip-download", "--no-playlist",
         f"https://www.youtube.com/watch?v={video_id}"],
    )
    return json.loads(raw)


def iso_duration(seconds):
    """Seconds → ISO-8601 (PT1H2M3S) — the shape nde.js stores from the YouTube API."""
    try:
        total = int(round(float(seconds)))
    except (TypeError, ValueError):
        return ""
    if total <= 0:
        return ""
    h, rem = divmod(total, 3600)
    m, s = divmod(rem, 60)
    out = "PT"
    if h:
        out += f"{h}H"
    if m:
        out += f"{m}M"
    if s or (not h and not m):
        out += f"{s}S"
    return out


def upload_date_iso(upload_date):
    """yt-dlp's 'YYYYMMDD' → the ISO timestamp shape nde.js stores in publishedAt."""
    s = str(upload_date or "").strip()
    if not re.match(r"^\d{8}$", s):
        return ""
    return f"{s[0:4]}-{s[4:6]}-{s[6:8]}T00:00:00Z"


def pick_caption_lang(meta):
    """Prefer a MANUAL English track; fall back to auto-generated English.

    Returns (lang_code, auto_generated) or (None, False) when there are no
    English captions at all.
    """
    def best(tracks):
        if not tracks:
            return None
        langs = [k for k in tracks.keys() if re.match(r"^en(\b|[-_.]|$)", k, re.I)]
        if not langs:
            return None
        # exact "en" first, then en-US/en-GB/en-orig…
        langs.sort(key=lambda k: (0 if k.lower() == "en" else 1, len(k), k))
        return langs[0]

    manual = best(meta.get("subtitles") or {})
    if manual:
        return manual, False
    auto = best(meta.get("automatic_captions") or {})
    if auto:
        return auto, True
    return None, False


def json3_to_segments(data):
    """YouTube json3 caption events → the transcript.segments shape nde.js writes.

    [{ start: seconds, dur: seconds, text }] with whitespace collapsed and
    empty events dropped — byte-for-byte the same conversion nde.js does.
    """
    segments = []
    for ev in (data.get("events") or []):
        segs = ev.get("segs")
        if not segs:
            continue
        text = "".join(s.get("utf8", "") or "" for s in segs)
        text = re.sub(r"\s+", " ", text).strip()
        if not text:
            continue
        segments.append({
            "start": (ev.get("tStartMs") or 0) / 1000,
            "dur": (ev.get("dDurationMs") or 0) / 1000,
            "text": text,
        })
    return segments


def download_captions(binary, video_id, lang, auto, workdir):
    # Clear any caption file left by an earlier run (--keep reuses the folder)
    # so we never parse a stale one.
    for f in os.listdir(workdir):
        if f.startswith(video_id) and f.endswith(".json3"):
            os.remove(os.path.join(workdir, f))
    flag = "--write-auto-subs" if auto else "--write-subs"
    run_ytdlp(binary, [
        "--skip-download", "--no-playlist", flag,
        "--sub-langs", lang, "--sub-format", "json3",
        "-o", os.path.join(workdir, "%(id)s.%(ext)s"),
        f"https://www.youtube.com/watch?v={video_id}",
    ])
    files = [f for f in os.listdir(workdir) if f.startswith(video_id) and f.endswith(".json3")]
    if not files:
        raise RuntimeError("yt-dlp wrote no json3 caption file")
    path = os.path.join(workdir, sorted(files)[0])
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    segments = json3_to_segments(data)
    if not segments:
        raise RuntimeError("caption file had no text")
    full = re.sub(r"\s+", " ", " ".join(s["text"] for s in segments)).strip()
    return {
        "source": "yt-dlp",
        "language": lang,
        "autoGenerated": bool(auto),
        "segments": segments,
        "full": full,
        "fetchedAt": now_iso(),
    }


def download_audio(binary, video_id, workdir, audio_format):
    """bestaudio, matching what's already banked (webm/opus, no re-encode).

    --audio-format mp3|m4a re-encodes through ffmpeg instead.
    """
    args = ["--no-playlist", "-o", os.path.join(workdir, "%(id)s.%(ext)s")]
    if audio_format == "source":
        # Prefer the webm/opus stream — every file already banked is .webm, and
        # editor.js's fallback URL assumes that extension.
        args += ["-f", "bestaudio[ext=webm]/bestaudio/best"]
    else:
        args += ["-f", "bestaudio/best", "--extract-audio",
                 "--audio-format", audio_format, "--audio-quality", "0"]
    run_ytdlp(binary, args + [f"https://www.youtube.com/watch?v={video_id}"])
    files = [
        f for f in os.listdir(workdir)
        if f.startswith(video_id + ".") and not f.endswith(".json3") and not f.endswith(".part")
    ]
    if not files:
        raise RuntimeError("yt-dlp wrote no audio file")
    if audio_format != "source":
        exact = [f for f in files if f.endswith("." + audio_format)]
        files = exact or files
    path = os.path.join(workdir, sorted(files, key=lambda f: os.path.getsize(os.path.join(workdir, f)))[-1])
    return path, path.rsplit(".", 1)[-1].lower()


# ── Firebase ───────────────────────────────────────────────────────────

def find_key_file():
    """No env vars set? Look for the Deck Factory key file in the obvious Mac
    spots — an AirDropped file lands in ~/Downloads. Filename just has to look
    like a Firebase service-account key; the newest valid one wins."""
    home = os.path.expanduser("~")
    hints = ("deckfactory", "firebase-adminsdk", "firebaseadminsdk", "service-account", "service_account")
    cands = []
    for d in ("Downloads", "Desktop", "Documents", "keys"):
        folder = os.path.join(home, d)
        try:
            names = os.listdir(folder)
        except OSError:
            continue
        for n in names:
            if n.lower().endswith(".json") and any(h in n.lower() for h in hints):
                cands.append(os.path.join(folder, n))

    def valid(p):
        try:
            with open(p, "r", encoding="utf-8") as fh:
                info = json.load(fh)
            return (info.get("type") == "service_account" and info.get("private_key")
                    and str(info.get("project_id", "")).startswith("deckfactory"))
        except Exception:
            return False

    for p in sorted(cands, key=os.path.getmtime, reverse=True):
        if valid(p):
            return p
    return None


def load_credentials():
    """GOOGLE_APPLICATION_CREDENTIALS (path) or FIREBASE_SERVICE_ACCOUNT (inline
    JSON) — and when neither is set, the key file is auto-found in ~/Downloads /
    ~/Desktop / ~/Documents / ~/keys (AirDrop drops it in Downloads).

    Returns (credentials, project_id). The key material is never printed or
    written anywhere.
    """
    from google.oauth2 import service_account

    inline = os.environ.get("FIREBASE_SERVICE_ACCOUNT", "").strip()
    path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "").strip()
    info = None
    if path:
        if not os.path.exists(path):
            raise SystemExit(f"GOOGLE_APPLICATION_CREDENTIALS points at a missing file: {path}")
        with open(path, "r", encoding="utf-8") as fh:
            info = json.load(fh)
    elif inline:
        try:
            info = json.loads(inline)
        except json.JSONDecodeError:
            raise SystemExit("FIREBASE_SERVICE_ACCOUNT is set but is not valid JSON")
    if not info:
        found = find_key_file()
        if found:
            log(f"Using key file: {found}")
            with open(found, "r", encoding="utf-8") as fh:
                info = json.load(fh)
    if not info:
        raise SystemExit(
            "No key file found. AirDrop the Deck Factory service-account JSON to this "
            "Mac (it lands in ~/Downloads) and run this again — it's found there "
            "automatically. Power-user alternative: set GOOGLE_APPLICATION_CREDENTIALS "
            "or FIREBASE_SERVICE_ACCOUNT."
        )
    project = info.get("project_id")
    if not project:
        raise SystemExit("service account JSON has no project_id")
    creds = service_account.Credentials.from_service_account_info(info)
    return creds, project


def bucket_name(project, override):
    return override or os.environ.get("NDE_BUCKET") or f"{project}.firebasestorage.app"


# ── per-video work ─────────────────────────────────────────────────────

def grab_one(video_id, ctx):
    """Returns 'done' | 'skipped' and raises on failure."""
    doc_ref = ctx["db"].collection(ctx["collection"]).document(video_id)
    snap = doc_ref.get()
    existing = snap.to_dict() if snap.exists else {}

    # A transcript counts whether it lives ON the doc (`full`) or as a Storage
    # pointer (`storage`) — the multi-hour audiobooks are too big for a doc.
    has_transcript = bool((existing.get("transcript") or {}).get("full")
                          or (existing.get("transcript") or {}).get("storage"))
    blob_ext = None
    audio_url = existing.get("audioUrl") or ""
    if audio_url:
        blob_ext = audio_url.rsplit(".", 1)[-1]
    blob = None
    if blob_ext:
        blob = ctx["bucket"].blob(f"{AUDIO_PREFIX}{video_id}.{blob_ext}")
        if not blob.exists():
            blob = None

    # The doc is written LAST, so an interrupted run can leave the audio banked
    # with no doc at all (it happened to 4 of the 7 Dolores Cannon audiobooks —
    # ~1.6GB already uploaded, invisible because there was nothing pointing at
    # it). Never trust the doc as the only record of what's in Storage: when it
    # can't tell us, ASK Storage directly before re-downloading hours of audio.
    if blob is None:
        for ext in CONTENT_TYPES:
            probe = ctx["bucket"].blob(f"{AUDIO_PREFIX}{video_id}.{ext}")
            if probe.exists():
                blob = probe
                blob_ext = ext
                log(f"    found audio already in Storage (.{ext}) with no doc — "
                    "re-using it instead of downloading again")
                break

    if has_transcript and blob is not None and not ctx["force"]:
        log(f"    already banked (transcript + audio) — skipping")
        return "skipped"

    meta = fetch_meta(ctx["ytdlp"], video_id)
    title = meta.get("title") or existing.get("title") or ""
    log(f"    {title[:70]}")

    update = {
        "videoId": video_id,
        "url": f"https://www.youtube.com/watch?v={video_id}",
        "updatedAt": now_iso(),
    }
    if title:
        update["title"] = title
    published = upload_date_iso(meta.get("upload_date"))
    if published:
        update["publishedAt"] = published
    if meta.get("channel") or meta.get("uploader"):
        update["channelTitle"] = meta.get("channel") or meta.get("uploader")
    if meta.get("channel_id"):
        update["channelId"] = meta["channel_id"]
    dur = iso_duration(meta.get("duration"))
    if dur:
        update["duration"] = dur
    if meta.get("description"):
        update["description"] = str(meta["description"])[:4000]
    if not existing:
        update["createdAt"] = now_iso()

    # 1) captions
    transcript_ok = has_transcript
    if not has_transcript or ctx["force"]:
        lang, auto = pick_caption_lang(meta)
        if not lang:
            log("    WARNING: no English captions on this video — audio only, "
                "transcript missing (moment mining will skip it)")
        else:
            transcript = download_captions(ctx["ytdlp"], video_id, lang, auto, ctx["workdir"])
            transcript_ok = True
            kind = "auto" if auto else "manual"
            log(f"    transcript ✓ {len(transcript['segments'])} segments, "
                f"{len(transcript['full']):,} chars ({kind} {lang})")
            # Firestore documents cap at 1MiB, and a multi-hour audiobook's
            # transcript alone can pass it — the write then dies with an opaque
            # 120s "write operation timed out". Oversized transcripts are banked
            # as JSON in Storage instead, with a small pointer on the doc
            # (editor.js loadVideo inflates it transparently).
            payload = json.dumps(transcript, ensure_ascii=False).encode("utf-8")
            if len(payload) > 850_000:
                dest = f"nde-transcripts/{video_id}.json"
                ctx["bucket"].blob(dest).upload_from_string(
                    payload, content_type="application/json")
                update["transcript"] = {
                    "storage": dest,
                    "segmentsCount": len(transcript["segments"]),
                    "chars": len(transcript["full"]),
                    "autoGenerated": transcript.get("autoGenerated"),
                    "language": transcript.get("language"),
                    "source": transcript.get("source"),
                }
                log(f"    too big for a Firestore doc ({len(payload) / 1e6:.1f}MB) "
                    f"— banked at {dest}, pointer on the doc")
            else:
                update["transcript"] = transcript
    else:
        log("    transcript already stored")

    # 2) audio
    if blob is None or ctx["force"]:
        path, ext = download_audio(ctx["ytdlp"], video_id, ctx["workdir"], ctx["audio_format"])
        size = os.path.getsize(path)
        dest = f"{AUDIO_PREFIX}{video_id}.{ext}"
        target = ctx["bucket"].blob(dest)
        target.upload_from_filename(path, content_type=CONTENT_TYPES.get(ext, "application/octet-stream"))
        target.make_public()
        update["audioUrl"] = f"https://storage.googleapis.com/{ctx['bucket'].name}/{dest}"
        update["audioBytes"] = size
        log(f"    audio ✓ {size / 1e6:.0f}MB → {dest}")
        if ext != "webm":
            log(f"    note: banked as .{ext} (every other video is .webm) — the doc's "
                "audioUrl points at it, so the cutter still finds it")
        if not ctx["keep"]:
            try:
                os.remove(path)
            except OSError:
                pass
    else:
        log("    audio already banked")
        # Heal a doc that never recorded the audio it actually has (the
        # interrupted-run case above), so the cutter can find it from now on.
        if not audio_url and blob_ext:
            dest = f"{AUDIO_PREFIX}{video_id}.{blob_ext}"
            update["audioUrl"] = f"https://storage.googleapis.com/{ctx['bucket'].name}/{dest}"
            try:
                blob.reload()
                if blob.size:
                    update["audioBytes"] = int(blob.size)
            except Exception:
                pass
            log(f"    recorded the existing audio on the doc → {dest}")

    # 3) status — never downgrade a doc that already has extracted moments.
    if existing.get("moments"):
        update["status"] = existing.get("status") or "extracted"
    elif transcript_ok:
        update["status"] = "transcribed"
    else:
        update["status"] = "pending"

    # merge=True: moments / summary / experiencerName / extractedAt survive.
    doc_ref.set(update, merge=True)
    log(f"    firestore ✓ {ctx['collection']}/{video_id} (status: {update['status']})")
    return "done"


# ── main ───────────────────────────────────────────────────────────────

def extract_ids_from_text(text):
    """Every video id found anywhere in a pasted blob — share links in any
    shape, separated by newlines, commas, spaces, or surrounding chatter. Bare
    11-char tokens count only when they look like an id (contain a digit,
    uppercase letter, '-' or '_') so ordinary words never match."""
    ids, seen = [], set()
    for m in URL_ID_RE.finditer(text or ""):
        vid = m.group(1)
        if vid not in seen:
            seen.add(vid)
            ids.append(vid)
    for tok in re.split(r"[\s,]+", text or ""):
        if ID_RE.match(tok) and re.search(r"[0-9A-Z_-]", tok) and tok not in seen:
            seen.add(tok)
            ids.append(tok)
    return ids


def collect_inputs(args):
    raw = []
    for item in args.urls:
        # a single CLI arg may carry several links joined by commas/whitespace
        for piece in re.split(r"[\s,]+", item):
            if piece:
                raw.append(piece)
    if args.file:
        with open(args.file, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.split("#", 1)[0].strip()
                if line:
                    raw.append(line)
    return raw


def resolve_ids(raw, args, ytdlp):
    """raw inputs → ordered, de-duplicated video ids."""
    ids, seen, bad = [], set(), []
    for item in raw:
        if is_playlist_url(item):
            if not args.yes_playlist:
                bad.append(f"{item} — that's a playlist URL. Pass --yes-playlist to grab every "
                           "video in it, or give me the individual watch links.")
                continue
            if args.dry_run:
                bad.append(f"{item} — playlist expansion needs the network (skipped in --dry-run)")
                continue
            log(f"expanding playlist {item}")
            for vid in expand_playlist(ytdlp, item):
                if vid not in seen:
                    seen.add(vid)
                    ids.append(vid)
            continue
        vid = parse_video_id(item)
        if not vid:
            bad.append(f"{item} — not a YouTube video URL or an 11-character video id")
            continue
        if vid not in seen:
            seen.add(vid)
            ids.append(vid)
    return ids, bad


def main():
    ap = argparse.ArgumentParser(
        prog="nde-grab-local.py",
        description="Download Anthony Chene interviews locally and bank audio + transcript in Firebase.",
    )
    ap.add_argument("urls", nargs="*", help="YouTube URLs or 11-character video ids")
    ap.add_argument("--file", help="text file with one url/id per line")
    ap.add_argument("--force", action="store_true", help="re-download and re-upload even if banked")
    ap.add_argument("--dry-run", action="store_true", help="print the plan; no network calls")
    ap.add_argument("--yes-playlist", action="store_true", help="expand playlist URLs")
    ap.add_argument("--audio-format", default="source", choices=["source", "mp3", "m4a"],
                    help="source (default, no re-encode — matches what's already banked)")
    ap.add_argument("--keep", help="keep downloads in this directory instead of a temp dir")
    ap.add_argument("--bucket", help="override the Storage bucket")
    ap.add_argument("--collection", default=COLLECTION, help=f"Firestore collection (default {COLLECTION})")
    args = ap.parse_args()

    raw = collect_inputs(args)
    if not raw:
        # Paste mode — run with nothing after the script name, then paste links.
        if sys.stdin.isatty():
            print("Paste your YouTube links below — any number, any format")
            print("(share links, commas, several lines: all fine).")
            print("Press Return on an empty line when you're done:")
            lines = []
            while True:
                try:
                    line = input()
                except EOFError:
                    break
                if not line.strip():
                    break
                lines.append(line)
            blob = "\n".join(lines)
        else:
            blob = sys.stdin.read()
        raw = extract_ids_from_text(blob)
        if not raw:
            raise SystemExit("No YouTube links found in what you pasted — nothing to do.")
        log(f"Found {len(raw)} video id(s).")

    ytdlp = ytdlp_bin()
    if not ytdlp and not args.dry_run:
        raise SystemExit("yt-dlp not found — install it with:  brew install yt-dlp ffmpeg")

    ids, bad = resolve_ids(raw, args, ytdlp)
    for msg in bad:
        log(f"SKIPPED  {msg}")
    if not ids:
        raise SystemExit("nothing to do — no usable video ids")

    creds, project = load_credentials()
    bucket = bucket_name(project, args.bucket)

    if args.dry_run:
        log(f"\nDRY RUN — nothing downloaded, nothing uploaded.")
        log(f"  project    {project}")
        log(f"  bucket     {bucket}")
        log(f"  collection {args.collection}")
        log(f"  audio      {'bestaudio, no re-encode' if args.audio_format == 'source' else args.audio_format}")
        log(f"  videos     {len(ids)}")
        for vid in ids:
            ext = "webm" if args.audio_format == "source" else args.audio_format
            log(f"    {vid}")
            log(f"      storage   gs://{bucket}/{AUDIO_PREFIX}{vid}.{ext}")
            log(f"      public    https://storage.googleapis.com/{bucket}/{AUDIO_PREFIX}{vid}.{ext}")
            log(f"      firestore {args.collection}/{vid}  (transcript + metadata, merged)")
        return 1 if bad else 0

    from google.cloud import firestore, storage

    db = firestore.Client(project=project, credentials=creds)
    gcs = storage.Client(project=project, credentials=creds)
    ctx = {
        "db": db,
        "bucket": gcs.bucket(bucket),
        "collection": args.collection,
        "ytdlp": ytdlp,
        "force": args.force,
        "audio_format": args.audio_format,
        "keep": bool(args.keep),
    }

    workdir = args.keep or tempfile.mkdtemp(prefix="nde-grab-")
    os.makedirs(workdir, exist_ok=True)
    ctx["workdir"] = workdir

    log(f"\nBanking {len(ids)} video(s) → {project} / {bucket}\n")
    done = skipped = failed = 0
    failures = []
    for i, vid in enumerate(ids, 1):
        log(f"[{i}/{len(ids)}] {vid}")
        try:
            result = grab_one(vid, ctx)
            if result == "skipped":
                skipped += 1
            else:
                done += 1
        except Exception as err:  # keep going; report at the end
            failed += 1
            failures.append((vid, str(err)))
            log(f"    FAILED: {err}")

    if not args.keep:
        shutil.rmtree(workdir, ignore_errors=True)

    log(f"\n{done} done · {skipped} skipped (already banked) · {failed} failed")
    for vid, err in failures:
        log(f"  FAILED {vid}: {err}")
    if failed or bad:
        log("Re-run the same command — finished videos are skipped, only the failures retry.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
